swagger: '2.0'


schemes: 
  - http
  - https
  
host: localhost:8085
basePath: /bank-api/v1

info:
  version: 1.0.0
  title: Bank API
  description: Adiministra a movimentacao bancaria do correntista e controla o acesso através do CPF e senha.
  termsOfService: http://8085/bank-api/v1/termo-uso
  contact: 
    name: Suporte 
    url: http://8085/bank-api/v1/contato
    email: suporte@bank.com

securityDefinitions:
  BasicAuth:
    type: basic
    
security: 
  - BasicAuth: []
  
consumes:  
  - application/json
produces: 
  - application/json
    
tags: 
  - name: Cliente
  - name: Conta
  - name: Extrato
  - name: Transacao

paths:
  '/cliente':
    post:
      tags:
        - Cliente
      summary: Cadastra Cliente
      description: Cadastra um novo cliente
      operationId: cadastraCliente
      parameters:
        - in: body
          name: cliente_
          schema: 
            $ref: '#/definitions/Cliente'
      responses:
        201:
          description: Cadastro efetuado co sucesso
          schema: 
           $ref: '#/definitions/Cliente'
        400:
          description: Requisicao invalida
        500: 
          description: Erro interno no serrvidor
          
          
  '/conta/{agencia}/{numConta}/{digito}/saldo':
    get:
      tags:
        - Conta
      summary: Consulta Saldo
      description: Consulta o saldo da conta do cliente.
      operationId: consultaSaldo
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: agencia
          type: integer
          format: int32
          required: true
        - in: path
          name: numConta
          type: integer
          format: int64
          required: true
        - in: path
          name: digito
          type: integer
          format: int32
          required: true
        - in: header
          name: Authorization
          type: string
          required: true
      responses:
        200:
          description: Consulta a saldo efetuada com sucesso
          schema:
            type: number
            format: double
            example: 134.68
        400:
          description: Requisição inválida
        401:
          description: Requisição não autorizada
        500:
          description: Erro no servidor
  
  '/transacao':
    post:
      tags:
        - Transacao
      summary: Cadastra Transação na conta 
      description:  Cadastra uma transacao de débito ou depósito na conta.
      security:
        - BasicAuth: []
      operationId: Cadastra transacao
      parameters:
        - in: header
          type: string
          name: Authorization
          required: true
        - in: body
          name: transacao
          schema:
            $ref: '#/definitions/Transacao'
          required: true  
        - in: query
          name: tipo
          type: string
          enum:
            - debito
            - deposito
          required: true
      
      responses:
        201:
          description: Cadastro de transacao efetuado com sucesso. 
          schema:
            $ref: '#/definitions/Transacao'
        400:
          description: Requisição inválida
        401:
          description: Requisição não autorizada
        500:
          description: Erro no servidor   
          
  '/extrato/{agencia}/{numConta}/{digito}':
    get:
      tags:
        - Extrato
      summary: Consulta Extrato
      description: Consulta o extrato da conta do cliente.
      operationId: consultaExtrato
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: agencia
          type: integer
          format: int32
          required: true
        - in: path
          name: numConta
          type: integer
          format: int64
          required: true
        - in: path
          name: digito
          type: integer
          format: int32
          required: true
        - in: header
          name: Authorization
          type: string
          required: true
      responses:
        200:
          description: Consulta de extrato efetuada com sucesso
          schema:
            $ref: '#/definitions/Extrato'
        400:
          description: Requisição inválida
        401:
          description: Requisição não autorizada
        500:
          description: Erro no servidor 
  
  '/transacao/{codigo}':
    put:
      tags:
        - Transacao
      summary: Atualiza o valor da transacao
      description: Atualiza valor da transação existente na conta do cliente.
      operationId: atualizaTransacao
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: codigo
          required: true
          type: integer
          format: int64
        - in: query
          name: valor
          type: number
          format: double
          required: true
        - in: header
          name: Authorization
          type: string
          required: true
      responses:
        204:
          description: Valor atualizado com sucesso
        400:
          description: Requisição inválida
        401:
          description: Requisição não autorizada
        500:
          description: Erro no servidor 
    delete:
      tags:
        - Transacao
      summary: Deletar uma transação
      description: Deletar uma transação existente.
      operationId: excluirTransacao
      security:
        - BasicAuth: []
      parameters:
        - in: path
          name: codigo
          required: true
          type: integer
          format: int64
        - in: header
          name: Authorization
          type: string
          required: true
      responses:
        204:
          description: Transação deletada com sucesso
        400:
          description: Requisição inválida
        401:
          description: Requisição não autorizada
        500:
          description: Erro no servidor
    
  
definitions:
  Cliente:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
        titular:
          type: string 
          example: Eliara Costa
        cpf:
          type: string
          maxLength: 14
          minLength: 14
          example: 01234567891234
        senha: 
          type: string
          format: password
          example: senha123
        conta: 
          type: array
          items: 
            $ref: '#/definitions/Conta'
  Conta:
      type: object
      properties:
        agencia:
          type: string
          maxLength: 4
          minLength: 4
          example: 2779
        numConta: 
          type: string
          maxLength: 7
          minLength: 7
          example: 0023148
        digito:
          type: integer
          format: int32
          minLength: 1
          maxLength: 1
          example: 5
        saldo:
          type: number
          format: double
          example: 105.35
        cliente: 
          $ref: '#/definitions/Cliente'
        transacao:
          type: array
          items:
            $ref: '#/definitions/Transacao'
          
  Transacao:
      type: object
      properties:
        id:
          type: integer
          format: int64
        tipo:
          type: string
          enum:
            - debito 
            - deposito
        valor:
          type: number
          format: double
        data:
          type: string
          format: date-time
        conta:
          $ref: '#/definitions/Conta'
          
  Extrato:
      type: object
      properties:
        transacoes:
          type: array
          items:
            $ref: '#/definitions/Transacao'

      